# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "go.opentelemetry.io/otel"
      - dependency-name: "go.opentelemetry.io/otel/exporters*"
      - dependency-name: "go.opentelemetry.io/otel/sdk*"

  - package-ecosystem: "gomod"
    directory: "/tests/suite"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "go.opentelemetry.io/*"

  - package-ecosystem: "gomod"
    directory: "/tests/mssql"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "go.opentelemetry.io/*"
      - dependency-name: "github.com/Masterminds/squirrel"
      - dependency-name: "github.com/nhatthm/go-clock"
      - dependency-name: "github.com/nhatthm/testcontainers-go-*"

  - package-ecosystem: "gomod"
    directory: "/tests/mysql"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "go.opentelemetry.io/*"
      - dependency-name: "github.com/Masterminds/squirrel"
      - dependency-name: "github.com/nhatthm/go-clock"
      - dependency-name: "github.com/nhatthm/testcontainers-go-*"

  - package-ecosystem: "gomod"
    directory: "/tests/postgres"
    schedule:
      interval: "daily"
    ignore:
        - dependency-name: "go.opentelemetry.io/*"
        - dependency-name: "github.com/Masterminds/squirrel"
        - dependency-name: "github.com/nhatthm/go-clock"
        - dependency-name: "github.com/nhatthm/testcontainers-go-*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
