# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - contextcheck
    - copyloopvar
    - depguard
    - exhaustruct
    - execinquery
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoglobals
    - err113
    - gomnd
    - gomoddirectives
    - intrange
    - ireturn
    - lll
    - mnd
    - nolintlint # https://github.com/golangci/golangci-lint/issues/3063
    - nonamedreturns
    - paralleltest
    - perfsprint
    - rowserrcheck # https://github.com/golangci/golangci-lint/issues/2649
    - sqlclosecheck # https://github.com/golangci/golangci-lint/issues/2649
    - tagalign
    - tagliatelle
    - testifylint
    - testpackage
    - varnamelen
    - wastedassign # https://github.com/golangci/golangci-lint/issues/2649
    - wrapcheck

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - containedctx
        - dupl
        - execinquery
        - funlen
        - goconst
        - goerr113
        - gomnd
        - maintidx
        - mnd
        - nilnil
        - noctx
        - rowserrcheck
      path: "_test.go"
