name: lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  lint:
    name: lint
    strategy:
      fail-fast: false
      matrix:
        module: [ ".", "tests/suite", "tests/mysql", "tests/postgres" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.17.x

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.44.0

          # Optional: working directory, useful for monorepos
          working-directory: ${{ matrix.module }}

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go.
          # skip-go-installation: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true

      - name: gherkin-lint
        uses: nhatthm/gherkin-lint-action@v1.0.0
        with:
          feature_files: tests/features/*
          config_file: tests/.gherkin-lintrc
