---
name: lint

on:
  push:
    branches:
      - master

env:
  GO_VERSION: 1.20.x

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-go:
    name: lint
    strategy:
      fail-fast: false
      matrix:
        module: [ ".", "tests/suite", "tests/mssql", "tests/mysql", "tests/postgres" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
            go-version: ${{ env.GO_VERSION }}

      - id: vars
        run: |
          make $GITHUB_OUTPUT

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ steps.vars.outputs.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ matrix.module }}
          args: --timeout=5m

  lint-gherkin:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: gherkin-lint
        uses: nhatthm/gherkin-lint-action@v1.0.0
        with:
          feature_files: tests/features/*
          config_file: tests/.gherkin-lintrc
