name: lint

on:
  push:
    tags:
      - v*
    branches:
      - master

env:
  GO_VERSION: 1.18
  GOLANGCI_LINT_VERSION: v1.48.0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    strategy:
      fail-fast: false
      matrix:
        module: [ ".", "tests/suite", "tests/mssql", "tests/mysql", "tests/postgres" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
            go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ matrix.module }}

      - name: gherkin-lint
        uses: nhatthm/gherkin-lint-action@v1.0.0
        with:
          feature_files: tests/features/*
          config_file: tests/.gherkin-lintrc
