---
name: lint

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-go:
    name: lint
    strategy:
      fail-fast: false
      matrix:
        module: [ ".", "tests/suite", "tests/mssql", "tests/mysql", "tests/postgres" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - name: Setup
        uses: nhatthm/gh-actions/find-go-version@master

      - name: Install Go
        uses: nhatthm/gh-actions/setup-go@master
        with:
          go-version: ${{ env.GO_LATEST_VERSION }}

      - name: Lint
        uses: nhatthm/gh-actions/golangci-lint@master
        with:
          working-directory: ${{ matrix.module }}
          args: --timeout=5m

  lint-gherkin:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - name: Lint
        uses: nhatthm/gh-actions/gherkin-lint@master
        with:
          feature_files: tests/features/*
          config_file: tests/.gherkin-lintrc
