---
name: compatibility-test-mssql

on:
  push:
    branches:
      - master

env:
  GO111MODULE: "on"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.20.x, 1.21.x ]
        arch: [ "386", amd64 ]
        mssql-version: [ "2019" ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Go cache
        uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-mssql-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-mssql-cache

      - name: Test
        id: test
        env:
          GOARCH: ${{ matrix.arch }}
          MSSQL_VERSION: ${{ matrix.mssql-version }}-latest
        run: |
          make test-compatibility-mssql
