---
name: compatibility-test-mysql

on:
  push:
    branches:
      - master

env:
  GO111MODULE: "on"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.find-go-version.outputs.go-version }}
      go-latest-version: ${{ steps.find-go-version.outputs.go-latest-version }}
      go-supported-versions: ${{ steps.find-go-version.outputs.go-supported-versions }}
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - id: find-go-version
        name: Find Go version
        uses: nhatthm/gh-actions/find-go-version@master

  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJson(needs.setup.outputs.go-supported-versions) }}
        arch: [ "386", amd64 ]
        mysql-version: [ "8" ]
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - name: Install Go
        uses: nhatthm/gh-actions/setup-go@master
        with:
          go-version: ${{ matrix.go-version }}
          cache-key: ${{ runner.os }}-go-${{ matrix.go-version }}-mysql-cache-${{ hashFiles('**/go.sum') }}
          cache-restore-keys: ${{ runner.os }}-go-${{ matrix.go-version }}-mysql-cache

      - name: Test
        id: test
        env:
          GOARCH: ${{ matrix.arch }}
          MYSQL_VERSION: ${{ matrix.mysql-version }}
        run: |
          make test-compatibility-mysql
